/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { CollaborateurService } from "../collaborateur.service";
import { CollaborateurCreateInput } from "./CollaborateurCreateInput";
import { Collaborateur } from "./Collaborateur";
import { CollaborateurFindManyArgs } from "./CollaborateurFindManyArgs";
import { CollaborateurWhereUniqueInput } from "./CollaborateurWhereUniqueInput";
import { CollaborateurUpdateInput } from "./CollaborateurUpdateInput";
import { EntreeSortieFindManyArgs } from "../../entreeSortie/base/EntreeSortieFindManyArgs";
import { EntreeSortie } from "../../entreeSortie/base/EntreeSortie";
import { EntreeSortieWhereUniqueInput } from "../../entreeSortie/base/EntreeSortieWhereUniqueInput";

export class CollaborateurControllerBase {
  constructor(protected readonly service: CollaborateurService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Collaborateur })
  async createCollaborateur(
    @common.Body() data: CollaborateurCreateInput
  ): Promise<Collaborateur> {
    return await this.service.createCollaborateur({
      data: data,
      select: {
        createdAt: true,
        dateDepart: true,
        dateEmbauche: true,
        dateEntreePoste: true,
        departement: true,
        equipeNPlusUn: true,
        id: true,
        mailProfessionnel: true,
        matriculePaie: true,
        nom: true,
        numeroTel: true,
        poste: true,
        prenom: true,
        service: true,
        siteProduction: true,
        teletravail: true,
        updatedAt: true,
        wdId: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Collaborateur] })
  @ApiNestedQuery(CollaborateurFindManyArgs)
  async collaborateurs(
    @common.Req() request: Request
  ): Promise<Collaborateur[]> {
    const args = plainToClass(CollaborateurFindManyArgs, request.query);
    return this.service.collaborateurs({
      ...args,
      select: {
        createdAt: true,
        dateDepart: true,
        dateEmbauche: true,
        dateEntreePoste: true,
        departement: true,
        equipeNPlusUn: true,
        id: true,
        mailProfessionnel: true,
        matriculePaie: true,
        nom: true,
        numeroTel: true,
        poste: true,
        prenom: true,
        service: true,
        siteProduction: true,
        teletravail: true,
        updatedAt: true,
        wdId: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Collaborateur })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async collaborateur(
    @common.Param() params: CollaborateurWhereUniqueInput
  ): Promise<Collaborateur | null> {
    const result = await this.service.collaborateur({
      where: params,
      select: {
        createdAt: true,
        dateDepart: true,
        dateEmbauche: true,
        dateEntreePoste: true,
        departement: true,
        equipeNPlusUn: true,
        id: true,
        mailProfessionnel: true,
        matriculePaie: true,
        nom: true,
        numeroTel: true,
        poste: true,
        prenom: true,
        service: true,
        siteProduction: true,
        teletravail: true,
        updatedAt: true,
        wdId: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Collaborateur })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateCollaborateur(
    @common.Param() params: CollaborateurWhereUniqueInput,
    @common.Body() data: CollaborateurUpdateInput
  ): Promise<Collaborateur | null> {
    try {
      return await this.service.updateCollaborateur({
        where: params,
        data: data,
        select: {
          createdAt: true,
          dateDepart: true,
          dateEmbauche: true,
          dateEntreePoste: true,
          departement: true,
          equipeNPlusUn: true,
          id: true,
          mailProfessionnel: true,
          matriculePaie: true,
          nom: true,
          numeroTel: true,
          poste: true,
          prenom: true,
          service: true,
          siteProduction: true,
          teletravail: true,
          updatedAt: true,
          wdId: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Collaborateur })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteCollaborateur(
    @common.Param() params: CollaborateurWhereUniqueInput
  ): Promise<Collaborateur | null> {
    try {
      return await this.service.deleteCollaborateur({
        where: params,
        select: {
          createdAt: true,
          dateDepart: true,
          dateEmbauche: true,
          dateEntreePoste: true,
          departement: true,
          equipeNPlusUn: true,
          id: true,
          mailProfessionnel: true,
          matriculePaie: true,
          nom: true,
          numeroTel: true,
          poste: true,
          prenom: true,
          service: true,
          siteProduction: true,
          teletravail: true,
          updatedAt: true,
          wdId: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/entreeSorties")
  @ApiNestedQuery(EntreeSortieFindManyArgs)
  async findEntreeSorties(
    @common.Req() request: Request,
    @common.Param() params: CollaborateurWhereUniqueInput
  ): Promise<EntreeSortie[]> {
    const query = plainToClass(EntreeSortieFindManyArgs, request.query);
    const results = await this.service.findEntreeSorties(params.id, {
      ...query,
      select: {
        badgeTemporaire: true,

        collaborateur: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        dateHeureEntree: true,
        id: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/entreeSorties")
  async connectEntreeSorties(
    @common.Param() params: CollaborateurWhereUniqueInput,
    @common.Body() body: EntreeSortieWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      entreeSorties: {
        connect: body,
      },
    };
    await this.service.updateCollaborateur({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/entreeSorties")
  async updateEntreeSorties(
    @common.Param() params: CollaborateurWhereUniqueInput,
    @common.Body() body: EntreeSortieWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      entreeSorties: {
        set: body,
      },
    };
    await this.service.updateCollaborateur({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/entreeSorties")
  async disconnectEntreeSorties(
    @common.Param() params: CollaborateurWhereUniqueInput,
    @common.Body() body: EntreeSortieWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      entreeSorties: {
        disconnect: body,
      },
    };
    await this.service.updateCollaborateur({
      where: params,
      data,
      select: { id: true },
    });
  }
}
