/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Collaborateur } from "./Collaborateur";
import { CollaborateurCountArgs } from "./CollaborateurCountArgs";
import { CollaborateurFindManyArgs } from "./CollaborateurFindManyArgs";
import { CollaborateurFindUniqueArgs } from "./CollaborateurFindUniqueArgs";
import { CreateCollaborateurArgs } from "./CreateCollaborateurArgs";
import { UpdateCollaborateurArgs } from "./UpdateCollaborateurArgs";
import { DeleteCollaborateurArgs } from "./DeleteCollaborateurArgs";
import { EntreeSortieFindManyArgs } from "../../entreeSortie/base/EntreeSortieFindManyArgs";
import { EntreeSortie } from "../../entreeSortie/base/EntreeSortie";
import { CollaborateurService } from "../collaborateur.service";
@graphql.Resolver(() => Collaborateur)
export class CollaborateurResolverBase {
  constructor(protected readonly service: CollaborateurService) {}

  async _collaborateursMeta(
    @graphql.Args() args: CollaborateurCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Collaborateur])
  async collaborateurs(
    @graphql.Args() args: CollaborateurFindManyArgs
  ): Promise<Collaborateur[]> {
    return this.service.collaborateurs(args);
  }

  @graphql.Query(() => Collaborateur, { nullable: true })
  async collaborateur(
    @graphql.Args() args: CollaborateurFindUniqueArgs
  ): Promise<Collaborateur | null> {
    const result = await this.service.collaborateur(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Collaborateur)
  async createCollaborateur(
    @graphql.Args() args: CreateCollaborateurArgs
  ): Promise<Collaborateur> {
    return await this.service.createCollaborateur({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Collaborateur)
  async updateCollaborateur(
    @graphql.Args() args: UpdateCollaborateurArgs
  ): Promise<Collaborateur | null> {
    try {
      return await this.service.updateCollaborateur({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Collaborateur)
  async deleteCollaborateur(
    @graphql.Args() args: DeleteCollaborateurArgs
  ): Promise<Collaborateur | null> {
    try {
      return await this.service.deleteCollaborateur(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [EntreeSortie], { name: "entreeSorties" })
  async findEntreeSorties(
    @graphql.Parent() parent: Collaborateur,
    @graphql.Args() args: EntreeSortieFindManyArgs
  ): Promise<EntreeSortie[]> {
    const results = await this.service.findEntreeSorties(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
