/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Collaborateur as PrismaCollaborateur,
  EntreeSortie as PrismaEntreeSortie,
} from "@prisma/client";

export class CollaborateurServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.CollaborateurCountArgs, "select">
  ): Promise<number> {
    return this.prisma.collaborateur.count(args);
  }

  async collaborateurs(
    args: Prisma.CollaborateurFindManyArgs
  ): Promise<PrismaCollaborateur[]> {
    return this.prisma.collaborateur.findMany(args);
  }
  async collaborateur(
    args: Prisma.CollaborateurFindUniqueArgs
  ): Promise<PrismaCollaborateur | null> {
    return this.prisma.collaborateur.findUnique(args);
  }
  async createCollaborateur(
    args: Prisma.CollaborateurCreateArgs
  ): Promise<PrismaCollaborateur> {
    return this.prisma.collaborateur.create(args);
  }
  async updateCollaborateur(
    args: Prisma.CollaborateurUpdateArgs
  ): Promise<PrismaCollaborateur> {
    return this.prisma.collaborateur.update(args);
  }
  async deleteCollaborateur(
    args: Prisma.CollaborateurDeleteArgs
  ): Promise<PrismaCollaborateur> {
    return this.prisma.collaborateur.delete(args);
  }

  async findEntreeSorties(
    parentId: string,
    args: Prisma.EntreeSortieFindManyArgs
  ): Promise<PrismaEntreeSortie[]> {
    return this.prisma.collaborateur
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .entreeSorties(args);
  }
}
