/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  EntreeSortie as PrismaEntreeSortie,
  Collaborateur as PrismaCollaborateur,
} from "@prisma/client";

export class EntreeSortieServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.EntreeSortieCountArgs, "select">
  ): Promise<number> {
    return this.prisma.entreeSortie.count(args);
  }

  async entreeSorties(
    args: Prisma.EntreeSortieFindManyArgs
  ): Promise<PrismaEntreeSortie[]> {
    return this.prisma.entreeSortie.findMany(args);
  }
  async entreeSortie(
    args: Prisma.EntreeSortieFindUniqueArgs
  ): Promise<PrismaEntreeSortie | null> {
    return this.prisma.entreeSortie.findUnique(args);
  }
  async createEntreeSortie(
    args: Prisma.EntreeSortieCreateArgs
  ): Promise<PrismaEntreeSortie> {
    return this.prisma.entreeSortie.create(args);
  }
  async updateEntreeSortie(
    args: Prisma.EntreeSortieUpdateArgs
  ): Promise<PrismaEntreeSortie> {
    return this.prisma.entreeSortie.update(args);
  }
  async deleteEntreeSortie(
    args: Prisma.EntreeSortieDeleteArgs
  ): Promise<PrismaEntreeSortie> {
    return this.prisma.entreeSortie.delete(args);
  }

  async getCollaborateur(
    parentId: string
  ): Promise<PrismaCollaborateur | null> {
    return this.prisma.entreeSortie
      .findUnique({
        where: { id: parentId },
      })
      .collaborateur();
  }
}
