/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { EntreeSortieService } from "../entreeSortie.service";
import { EntreeSortieCreateInput } from "./EntreeSortieCreateInput";
import { EntreeSortie } from "./EntreeSortie";
import { EntreeSortieFindManyArgs } from "./EntreeSortieFindManyArgs";
import { EntreeSortieWhereUniqueInput } from "./EntreeSortieWhereUniqueInput";
import { EntreeSortieUpdateInput } from "./EntreeSortieUpdateInput";

export class EntreeSortieControllerBase {
  constructor(protected readonly service: EntreeSortieService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: EntreeSortie })
  async createEntreeSortie(
    @common.Body() data: EntreeSortieCreateInput
  ): Promise<EntreeSortie> {
    return await this.service.createEntreeSortie({
      data: {
        ...data,

        collaborateur: data.collaborateur
          ? {
              connect: data.collaborateur,
            }
          : undefined,
      },
      select: {
        badgeTemporaire: true,

        collaborateur: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        dateHeureEntree: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [EntreeSortie] })
  @ApiNestedQuery(EntreeSortieFindManyArgs)
  async entreeSorties(@common.Req() request: Request): Promise<EntreeSortie[]> {
    const args = plainToClass(EntreeSortieFindManyArgs, request.query);
    return this.service.entreeSorties({
      ...args,
      select: {
        badgeTemporaire: true,

        collaborateur: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        dateHeureEntree: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: EntreeSortie })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async entreeSortie(
    @common.Param() params: EntreeSortieWhereUniqueInput
  ): Promise<EntreeSortie | null> {
    const result = await this.service.entreeSortie({
      where: params,
      select: {
        badgeTemporaire: true,

        collaborateur: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        dateHeureEntree: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: EntreeSortie })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateEntreeSortie(
    @common.Param() params: EntreeSortieWhereUniqueInput,
    @common.Body() data: EntreeSortieUpdateInput
  ): Promise<EntreeSortie | null> {
    try {
      return await this.service.updateEntreeSortie({
        where: params,
        data: {
          ...data,

          collaborateur: data.collaborateur
            ? {
                connect: data.collaborateur,
              }
            : undefined,
        },
        select: {
          badgeTemporaire: true,

          collaborateur: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          dateHeureEntree: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: EntreeSortie })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteEntreeSortie(
    @common.Param() params: EntreeSortieWhereUniqueInput
  ): Promise<EntreeSortie | null> {
    try {
      return await this.service.deleteEntreeSortie({
        where: params,
        select: {
          badgeTemporaire: true,

          collaborateur: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          dateHeureEntree: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
