/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { EntreeSortie } from "./EntreeSortie";
import { EntreeSortieCountArgs } from "./EntreeSortieCountArgs";
import { EntreeSortieFindManyArgs } from "./EntreeSortieFindManyArgs";
import { EntreeSortieFindUniqueArgs } from "./EntreeSortieFindUniqueArgs";
import { CreateEntreeSortieArgs } from "./CreateEntreeSortieArgs";
import { UpdateEntreeSortieArgs } from "./UpdateEntreeSortieArgs";
import { DeleteEntreeSortieArgs } from "./DeleteEntreeSortieArgs";
import { Collaborateur } from "../../collaborateur/base/Collaborateur";
import { EntreeSortieService } from "../entreeSortie.service";
@graphql.Resolver(() => EntreeSortie)
export class EntreeSortieResolverBase {
  constructor(protected readonly service: EntreeSortieService) {}

  async _entreeSortiesMeta(
    @graphql.Args() args: EntreeSortieCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [EntreeSortie])
  async entreeSorties(
    @graphql.Args() args: EntreeSortieFindManyArgs
  ): Promise<EntreeSortie[]> {
    return this.service.entreeSorties(args);
  }

  @graphql.Query(() => EntreeSortie, { nullable: true })
  async entreeSortie(
    @graphql.Args() args: EntreeSortieFindUniqueArgs
  ): Promise<EntreeSortie | null> {
    const result = await this.service.entreeSortie(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => EntreeSortie)
  async createEntreeSortie(
    @graphql.Args() args: CreateEntreeSortieArgs
  ): Promise<EntreeSortie> {
    return await this.service.createEntreeSortie({
      ...args,
      data: {
        ...args.data,

        collaborateur: args.data.collaborateur
          ? {
              connect: args.data.collaborateur,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => EntreeSortie)
  async updateEntreeSortie(
    @graphql.Args() args: UpdateEntreeSortieArgs
  ): Promise<EntreeSortie | null> {
    try {
      return await this.service.updateEntreeSortie({
        ...args,
        data: {
          ...args.data,

          collaborateur: args.data.collaborateur
            ? {
                connect: args.data.collaborateur,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => EntreeSortie)
  async deleteEntreeSortie(
    @graphql.Args() args: DeleteEntreeSortieArgs
  ): Promise<EntreeSortie | null> {
    try {
      return await this.service.deleteEntreeSortie(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Collaborateur, {
    nullable: true,
    name: "collaborateur",
  })
  async getCollaborateur(
    @graphql.Parent() parent: EntreeSortie
  ): Promise<Collaborateur | null> {
    const result = await this.service.getCollaborateur(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
